### ISSUE TITLE
Docs don't look right on narrower screens

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord.dev#317]
![Screenshot 2024-07-23 at 12 08 42](https://github.com/user-attachments/assets/d158f85a-6352-40d6-9475-2eef3327d948)

**Comment by t4lz** [comment]
I think this issue is back:

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/754a4d64-24f8-42b8-b5dc-13f6fd7da0c9">

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/33426a55-e4af-4c6a-85b7-7779b1d93f76">

Observed on a small macbook on Arc with the sidebar open.

**Comment by gememma** [comment]
Looks like this is an issue only on chromium, doesn't happen with firefox
